/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.junit.Test;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.Assert.*;

public class QuizTest {
    @Test public void testQuizRunUserCode() {
        Quiz classUnderTest = new Quiz();

        JSONParser parser = new JSONParser();
        try {
            ClassLoader classLoader = getClass().getClassLoader();
            File file = new File(classLoader.getResource("test_data.json").getFile());

            JSONArray testData = (JSONArray) parser.parse(new FileReader(file));
            for (Object o: testData)
            {
                JSONObject testEntry = (JSONObject) o;
                String input = (String) testEntry.get("input");
                String expectedOutput = (String) testEntry.get("expectedOutput");

                assertEquals(expectedOutput, classUnderTest.run(input));
            }
        } catch (ParseException | IOException e) {
            e.printStackTrace();
        }
    }
}
